name: 'Whitelist/Unwhitelist ip-range on GKE'
description: 'Whitelist/Unwhitelist ip/range on GKE private cluster'
inputs:
  zone:  # id of input
    description: 'Google Cloud zone'
    required: true
  cluster_id:  # id of input
    description: 'Google Cloud Kubernetes Cluster ID'
    required: true
  whitelist:  # id of input
    description: 'Whether to whitelist or the other way arround'
    required: false
    default: "true"
  cidr:  # id of input
    description: 'Ip range to whitelist or unwhitelist'
    required: true
  name:  # id of input
    description: 'Display name for the ip range'
    required: false
    default: "Github Action"


runs:
  using: 'node16'
  main: 'dist/index.js'
