name: 'Whitelist/Unwhitelist ip-range on GKE'
description: 'Whitelist/Unwhitelist ip/range on GKE private cluster'
inputs:
  cluster_id:  # id of input
    description: 'Google Cloud Kubernetes Cluster Name/ID'
    required: true
  location:  # id of input
    description: 'Zone/Region that Cluster is in'
    required: true
  whitelist:  # id of input
    description: 'Set to true to whitelist CIDR, false to remove'
    required: false
    default: "true"
  cidr:  # id of input
    description: 'Ip range to whitelist or remove from whitelist'
    required: true
  name:  # id of input
    description: 'Display name for the ip range'
    required: false
    default: "Github Action"


runs:
  using: 'node12'
  main: 'dist/index.js'
